### ISSUE TITLE
Does not seem to work with GHC v9.2.4

### ISSUE THREAD

**Issue by Qqwy** [utdemir/qualified-imports-plugin#1]
While compiling a project using this nice plugin in a repository using GHC 9.2.4 I get the following error at build time:

```
qualified-imports-plugin> configure                                                
qualified-imports-plugin> Configuring qualified-imports-plugin-0.0.1...
qualified-imports-plugin> build         
qualified-imports-plugin> Preprocessing library for qualified-imports-plugin-0.0.1..
qualified-imports-plugin> Building library for qualified-imports-plugin-0.0.1..
qualified-imports-plugin> [1 of 1] Compiling QualifiedImportsPlugin
qualified-imports-plugin>               
qualified-imports-plugin> /tmp/stack-51368181e2a25a1c/qualified-imports-plugin-0.0.1/src/QualifiedImportsPlugin.hs:81:13: error:
qualified-imports-plugin>     • Couldn't match expected type: SDoc -> t
qualified-imports-plugin>                   with actual type: MsgEnvelope DecoratedSDoc
qualified-imports-plugin>     • The function ‘mkPlainWarnMsg’
qualified-imports-plugin>       is applied to three value arguments,
qualified-imports-plugin>         but its type ‘SrcSpan -> SDoc -> MsgEnvelope DecoratedSDoc’
qualified-imports-plugin>         has only two
qualified-imports-plugin>       In the expression:
qualified-imports-plugin>         mkPlainWarnMsg
qualified-imports-plugin>           (hsc_dflags env)
qualified-imports-plugin>           (UnhelpfulSpan $ unhelpfulOther "QualifiedImportsPlugin")
qualified-imports-plugin>           ("Unknown argument:" <+> text x)
qualified-imports-plugin>       In an equation for ‘msg’:
qualified-imports-plugin>           msg 
qualified-imports-plugin>             = mkPlainWarnMsg
qualified-imports-plugin>                 (hsc_dflags env)
qualified-imports-plugin>                 (UnhelpfulSpan $ unhelpfulOther "QualifiedImportsPlugin")
qualified-imports-plugin>                 ("Unknown argument:" <+> text x)
qualified-imports-plugin>     • Relevant bindings include
qualified-imports-plugin>         msg :: t (bound at src/QualifiedImportsPlugin.hs:80:11)
qualified-imports-plugin>    |          
qualified-imports-plugin> 81 |             mkPlainWarnMsg
qualified-imports-plugin>    |             ^^^^^^^^^^^^^^...
qualified-imports-plugin>               
qualified-imports-plugin> /tmp/stack-51368181e2a25a1c/qualified-imports-plugin-0.0.1/src/QualifiedImportsPlugin.hs:82:16: error:
qualified-imports-plugin>     • Couldn't match expected type ‘SrcSpan’
qualified-imports-plugin>                   with actual type ‘DynFlags’
qualified-imports-plugin>     • In the first argument of ‘mkPlainWarnMsg’, namely
qualified-imports-plugin>         ‘(hsc_dflags env)’
qualified-imports-plugin>       In the expression:
qualified-imports-plugin>         mkPlainWarnMsg
qualified-imports-plugin>           (hsc_dflags env)
qualified-imports-plugin>           (UnhelpfulSpan $ unhelpfulOther "QualifiedImportsPlugin")
qualified-imports-plugin>           ("Unknown argument:" <+> text x)
qualified-imports-plugin>       In an equation for ‘msg’:
qualified-imports-plugin>           msg 
qualified-imports-plugin>             = mkPlainWarnMsg
qualified-imports-plugin>                 (hsc_dflags env)
qualified-imports-plugin>                 (UnhelpfulSpan $ unhelpfulOther "QualifiedImportsPlugin")
qualified-imports-plugin>                 ("Unknown argument:" <+> text x)
qualified-imports-plugin>    |          
qualified-imports-plugin> 82 |               (hsc_dflags env)
qualified-imports-plugin>    |                ^^^^^^^^^^^^^^
qualified-imports-plugin>               
qualified-imports-plugin> /tmp/stack-51368181e2a25a1c/qualified-imports-plugin-0.0.1/src/QualifiedImportsPlugin.hs:83:16: error:
qualified-imports-plugin>     • Couldn't match expected type ‘SDoc’ with actual type ‘SrcSpan’
qualified-imports-plugin>     • In the second argument of ‘mkPlainWarnMsg’, namely
qualified-imports-plugin>         ‘(UnhelpfulSpan $ unhelpfulOther "QualifiedImportsPlugin")’
qualified-imports-plugin>       In the expression:
qualified-imports-plugin>         mkPlainWarnMsg
qualified-imports-plugin>           (hsc_dflags env)
qualified-imports-plugin>           (UnhelpfulSpan $ unhelpfulOther "QualifiedImportsPlugin")
qualified-imports-plugin>           ("Unknown argument:" <+> text x)
qualified-imports-plugin>       In an equation for ‘msg’:
qualified-imports-plugin>           msg 
qualified-imports-plugin>             = mkPlainWarnMsg
qualified-imports-plugin>                 (hsc_dflags env)
qualified-imports-plugin>                 (UnhelpfulSpan $ unhelpfulOther "QualifiedImportsPlugin")
qualified-imports-plugin>                 ("Unknown argument:" <+> text x)
qualified-imports-plugin>    |          
qualified-imports-plugin> 83 |               (UnhelpfulSpan $ unhelpfulOther "QualifiedImportsPlugin")
qualified-imports-plugin>    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
qualified-imports-plugin>               
qualified-imports-plugin> /tmp/stack-51368181e2a25a1c/qualified-imports-plugin-0.0.1/src/QualifiedImportsPlugin.hs:168:33: error:
qualified-imports-plugin>     • Couldn't match type ‘SrcSpan’
qualified-imports-plugin>                      with ‘SrcSpanAnn' (EpAnn AnnListItem)’
qualified-imports-plugin>       Expected: Maybe (XRec GhcPs ModuleName)
qualified-imports-plugin>         Actual: Maybe (Located ModuleName)
qualified-imports-plugin>     • In the ‘ideclAs’ field of a record
qualified-imports-plugin>       In the fourth argument of ‘maybe’, namely
qualified-imports-plugin>         ‘(simpleImportDecl n)
qualified-imports-plugin>            {ideclQualified = QualifiedPre, ideclAs = Just (noLoc qn),
qualified-imports-plugin>             ideclImplicit = True}’
qualified-imports-plugin>       In the expression:
qualified-imports-plugin>         (maybe noLoc L loc)
qualified-imports-plugin>           (simpleImportDecl n)
qualified-imports-plugin>             {ideclQualified = QualifiedPre, ideclAs = Just (noLoc qn),
qualified-imports-plugin>              ideclImplicit = True}
qualified-imports-plugin>     |         
qualified-imports-plugin> 168 |                       ideclAs = Just (noLoc qn),
qualified-imports-plugin>     |                                 ^^^^^^^^^^^^^^^
qualified-imports-plugin>               
qualified-imports-plugin> /tmp/stack-51368181e2a25a1c/qualified-imports-plugin-0.0.1/src/QualifiedImportsPlugin.hs:173:30: error:
qualified-imports-plugin>     • Couldn't match type ‘SrcSpan’
qualified-imports-plugin>                      with ‘SrcSpanAnn' (EpAnn AnnListItem)’
qualified-imports-plugin>       Expected: [LImportDecl GhcPs]
qualified-imports-plugin>         Actual: [Located (ImportDecl GhcPs)]
qualified-imports-plugin>     • In the ‘hsmodImports’ field of a record
qualified-imports-plugin>       In the second argument of ‘($)’, namely
qualified-imports-plugin>         ‘m {hsmodImports = hsmodImports m ++ newImports}’
qualified-imports-plugin>       In a stmt of a 'do' block:
qualified-imports-plugin>         return $ m {hsmodImports = hsmodImports m ++ newImports}
qualified-imports-plugin>     |         
qualified-imports-plugin> 173 |   return $ m {hsmodImports = hsmodImports m ++ newImports}
qualified-imports-plugin>     |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
qualified-imports-plugin>               
qualified-imports-plugin> /tmp/stack-51368181e2a25a1c/qualified-imports-plugin-0.0.1/src/QualifiedImportsPlugin.hs:178:12: error:
qualified-imports-plugin>     • Variable not in scope: unitState :: DynFlags -> b
qualified-imports-plugin>     • Perhaps you meant data constructor ‘UnitState’ (imported from GHC.Plugins)
qualified-imports-plugin>     |         
qualified-imports-plugin> 178 |   let us = unitState $ hsc_dflags env
qualified-imports-plugin>     |            ^^^^^^^^^
Progress 22/23                          
````

It seems like some internals of GHC that this plugin depends on might have changed.

**Comment by utdemir** [comment]
Hi, thank you for the issue, I had no idea someone were looking at this! :)

I had a quick look. Can you try this branch if this solves your issue: https://github.com/utdemir/qualified-imports-plugin/tree/ud/ghc924support

**Comment by Qqwy** [comment]
Thanks for the fast response!

Yes, the version on that branch works perfectly with the new GHC version :blush:.

**Comment by utdemir** [comment]
Thanks! I merged it in :).
